import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState, useRef } from "react";
import { NZImageResult } from "@/models/nz-image-result";
import { RequestManager } from "@/managers/request-manager";

export default function Home() {
  const [result, setResult] = useState<NZImageResult | null>(null);
  const dataFetchedRef = useRef(false);
  const thirtySeconds = 30000;
  const requestManager = new RequestManager();

  function newImage() {
    requestManager.fetchImage(setResult);
  }

  // Triggers on every render. See: https://www.w3schools.com/react/react_useeffect.asp
  useEffect(() => {
    // Makes sure that the code below it only runs once
    if (dataFetchedRef.current) return;
    dataFetchedRef.current = true;

    // Fetch an image and update state
    newImage();

    // Then set an interval timer to get further new images every thirty seconds
    setInterval(newImage, thirtySeconds);
  });

  return (
    <>
      <Head>
        <title>NZImage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {result && (
            <div>
              <Image
                className={styles.image}
                src={result.largeThumbnailUrl}
                alt={result.title}
                fill
              />
              <div className={styles.text}>
                <h2>{result.title}</h2>
                {result.description != null && (
                  <p className={styles.description}>{result.description}</p>
                )}
                {result.displayCollection != null && (
                  <p className={styles.collection}>
                    {result.displayCollection}
                  </p>
                )}
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
